#!/usr/bin/perl -w
use strict;
use vars qw(%PREREQ %RECOMMEND %BUILDREQ);
use lib 'lib';

%BUILDREQ = (
    'Test::More'     => 0.40,
);

%PREREQ = (
    'Win32::OLE'     => 0,
    'CGI'            => 3.21,
    'HTML::Entities' => 0,
);

1;
